"""AI Editor data -> the AI Editor's exported .ai script (File > Export Script), text for text."""
import itertools

from ..formats import wai
from ..formats.wtg import FUNCTION, PRESET, STRING, VARIABLE
from ..gamedata.triggerdata import CALL, CONDITION, TriggerData
from ..ops.gui import RAWCODE_TYPES, script_name
from .build import banner, declaration

BAR = "//" + "=" * 75
HEROES = {b"1HIA": "hero_id", b"2HIA": "hero_id2", b"3HIA": "hero_id3"}
EMPTY = b"\0\0\0\0"
FIRST_HERO_ONLY = int.from_bytes(b"HAIA", "little")   # minimum forces: the first hero alone
OPTIONS = (("SetDefendPlayer", 0x8000), ("SetRandomPaths", 0x4000), ("SetTargetHeroes", 0x0002),
           ("SetPeonsRepair", 0x0004), ("SetHeroesFlee", 0x0008), ("SetHeroesBuyItems", 0x10000),
           ("SetUnitsFlee", 0x0010), ("SetGroupsFlee", 0x0020), ("SetWatchMegaTargets", 0x0040),
           ("SetIgnoreInjured", 0x0080), ("SetHeroesTakeItems", 0x0100), ("SetSlowChopping", 0x0200),
           ("SetCaptainChanges", 0x0400), ("SetSmartArtillery", 0x0800))
MELEE, REMOVE_INJURIES, SET_PLAYER_NAME = 0x0001, 0x1000, 0x2000


def ai_trigger_data(catalog) -> TriggerData:
    """TriggerData.txt plus the AI Editor's own functions (UI/AIEditorData.txt [AIFunctions])."""
    ai = (catalog._read("UI/AIEditorData.txt") or b"").replace(b"[AIFunctions]", b"[TriggerCalls]")
    return TriggerData.parse((catalog._read("UI/TriggerData.txt") or b"") + b"\r\n" + ai, catalog.westring)


def _comment(title: str) -> str:
    return f"{BAR}\n// {title}\n{BAR}\n"


class _Gen:
    def __init__(self, ai: wai.AIData, td: TriggerData):
        self.ai, self.td = ai, td
        self.names = {c.index: "gCond_" + script_name(c.condition.name) for c in ai.conditions}

    # ---- expressions -----------------------------------------------------------------------------------------
    def id(self, raw: bytes) -> str:
        return HEROES.get(raw) or f"'{raw.decode('latin-1')}'"

    def param(self, p, expected: str) -> str:
        if p.type == STRING:
            return f"'{p.value}'" if expected in RAWCODE_TYPES else p.value
        if p.type == PRESET:
            preset = self.td.presets.get(p.value)
            if preset is None or expected and not self.td.compatible(expected, preset.type):
                return "Error"   # the editor's text for a preset of the wrong type
            return preset.code
        if p.type == FUNCTION and p.call is not None:
            return self.call(p.call.name, p.call.params or [], p.call.kind)
        if p.type == VARIABLE:
            return p.value
        return "null"

    def call(self, name: str, params, kind: int = CALL) -> str:
        fn = self.td.function(kind, name) or self.td.function(CALL, name) or self.td.function(CONDITION, name)
        types = list(fn.args) if fn else [""] * len(params)
        args = [self.param(p, t) for p, t in zip(params, types)]
        if name.startswith("OperatorCompare") or name in ("OperatorInt", "OperatorReal"):
            return f"( {args[0]} {args[1]} {args[2]} )"
        if name in ("GetBooleanAnd", "GetBooleanOr"):
            return f"( {args[0]} {'and' if name == 'GetBooleanAnd' else 'or'} {args[1]} )"
        return f"{name}( {', '.join(args)} )" if args else f"{name}(  )"

    def test(self, index: int, condition: wai.Condition) -> str | None:
        """The text of an `if (...)` for a condition reference, None when there is none."""
        if index == wai.NO_CONDITION:
            return None
        if index == wai.CUSTOM_CONDITION:
            return self.call(condition.function, condition.params, CONDITION) if condition.function else "true"
        return self.names.get(index, "true")

    # ---- sections --------------------------------------------------------------------------------------------
    def header(self) -> str:
        return f"{BAR}\n// \n// {self.ai.name}\n// \n//   Warcraft III AI script\n//   Generated by the Warcraft III World Editor\n// \n{BAR}\n\n"

    def globals(self) -> str:
        lines = [declaration("integer", n, False, v) for n, v in
                 (("attackWave", "1"), ("nextDelay", "0"), ("awGold", "0"), ("awWood", "0"))]
        if self.ai.conditions:
            lines += ["", "    // Conditions"] + [declaration("boolean", self.names[c.index], False, "false")
                                                   for c in self.ai.conditions]
        return banner("Global Variables") + "\nglobals\n" + "".join(x + "\n" for x in lines) + "endglobals\n\n"

    def utilities(self) -> str:
        gold, wood = (self.id(w) for w in self.ai.workers[:2])
        return banner("Utility Functions") + UTILITIES.replace("{gold}", gold).replace("{wood}", wood)

    def options(self) -> str:
        lines = ["    call SetMeleeAI(  )" if self.ai.options & MELEE else "    call SetCampaignAI(  )"]
        lines += [f"    call {fn}( {'true' if self.ai.options & bit else 'false'} )" for fn, bit in OPTIONS]
        return (banner("Basic Options") + f"\n{BAR}\nfunction InitOptions takes nothing returns nothing\n"
                + "".join(x + "\n" for x in lines) + "endfunction\n\n")

    def conditions(self) -> str:
        lines = [f"    set {self.names[c.index]} = {self.test(wai.CUSTOM_CONDITION, c.condition)}"
                 for c in self.ai.conditions]
        return (banner("Conditions") + "\n" + _comment("Updates the values of all preset conditions")
                + "function UpdateConditions takes nothing returns nothing\n" + "".join(x + "\n" for x in lines)
                + "endfunction\n\n")

    def heroes(self) -> str:
        ai = self.ai
        present = [(i, h) for i, h in enumerate(ai.heroes) if h != EMPTY]
        body = []
        # one hero order per leading hero slot that is set; each lists every hero's skills for that order
        for order in range(len(list(itertools.takewhile(lambda h: h != EMPTY, ai.heroes)))):
            body.append(f"    {'if' if order == 0 else 'elseif'} (order == {order + 1}) then")
            body.append(f"        set {('hero_id', 'hero_id2', 'hero_id3')[order]} = heroid")
            for k, (i, h) in enumerate(present):
                body.append(f"        {'if' if k == 0 else 'elseif'} (heroid == {self.id(h)}) then")
                skills = ai.skills[i * 3 + order]
                body += [f"            set skills{order + 1}[{level:2d}] = {self.id(s)}" for level, s in enumerate(skills, 1)]
            body.append("        endif")
        if body:
            body.append("    endif")
        select = ["    local integer roll = GetRandomInt(1,100)"]
        choices = [(pct, perm) for pct, perm in zip(ai.hero_orders, itertools.permutations(range(3))) if pct]
        total = 0
        for k, (pct, perm) in enumerate(choices):
            calls = [f"call SetHero( {position}, {self.id(ai.heroes[slot])} )"
                     for position, slot in enumerate(perm, 1) if ai.heroes[slot] != EMPTY]
            if len(choices) == 1:
                select += ["    " + x for x in calls]
                continue
            total += pct
            select.append("    if (roll <= %d) then" % total if k == 0 else
                          "    else" if k == len(choices) - 1 else "    elseif (roll <= %d) then" % total)
            select += ["        " + x for x in calls]
        if len(choices) > 1:
            select.append("    endif")
        return (banner("Heroes") + "\n" + _comment("Stores hero ID and skills")
                + "function SetHero takes integer order, integer heroid returns nothing\n"
                + "".join(x + "\n" for x in body) + "endfunction\n\n"
                + _comment("Selects hero IDs for three possible heroes")
                + "function SelectHeroes takes nothing returns nothing\n" + "".join(x + "\n" for x in select)
                + "endfunction\n\n" + CHOOSE_HERO_SKILL)

    @staticmethod
    def town(town: int, harvest: bool = False) -> str:
        if town == -1:
            return "mine" if harvest else "-1"
        if town <= -3:
            return f"mine + {-3 - town}"
        return str(town)

    def blocks(self, entries, render) -> list[str]:
        """Lines for entries in order, consecutive ones with the same named condition sharing an if block."""
        out, open_key = [], None
        for e in entries:
            test = self.test(e.condition_index, e.condition)
            key = test   # the same named condition or the same custom condition text
            if open_key is not None and key != open_key:
                out.append("    endif")
                open_key = None
            if test is not None and open_key is None:
                out.append(f"    if ({test}) then")
                open_key = key
            ind = "        " if open_key is not None else "    "
            out += [ind + line for line in render(e)]
        if open_key is not None:
            out.append("    endif")
        return out

    def building(self) -> str:
        ai, counts = self.ai, {}

        def build(p):
            if p.kind == 2:
                return [f"call BuildExpansion( {self.id(ai.workers[2])}, {self.id(ai.workers[3])} )"]
            # counted per id for any town, per id and town otherwise
            for key in ((p.kind, p.id), (p.kind, p.id, p.town)):
                counts[key] = counts.get(key, 0) + 1
            n = counts[(p.kind, p.id) if p.town == -1 else (p.kind, p.id, p.town)]
            kind = "BUILD_UPGRADE" if p.kind == 1 else "BUILD_UNIT"
            return [f"call SetBuildAll( {kind}, {n}, {self.id(p.id)}, {self.town(p.town)} )"]

        def harvest(p):
            verb = "HarvestWood" if p.resource == 1 else "HarvestGold"
            where = self.town(p.town, True)
            if p.workers >= 0:
                return [f"set numWorkers = {p.workers}", f"call {verb}( {where}, numWorkers )"]
            total, busy = ("allWood", "awWood") if p.resource == 1 else ("allGold", "awGold")
            return [f"set numWorkers = {total}" + (f" - {busy}" if p.workers == -2 else ""),
                    "if (numWorkers > 0) then", f"    call {verb}( {where}, numWorkers )", "endif"]

        gold, wood = (self.id(w) for w in ai.workers[:2])
        return (banner("Building and Harvesting") + "\n" + _comment("Specifies building priorities for workers")
                + "function BuildPriorities takes nothing returns nothing\n    local integer mine = TownWithMine()\n"
                + "".join(x + "\n" for x in self.blocks(ai.build, build)) + "endfunction\n\n"
                + _comment("Specifies harvesting priorities for workers")
                + "function HarvestPriorities takes nothing returns nothing\n    local integer mine = TownWithMine()\n"
                + f"    local integer allGold = GetUnitCountDone({gold})\n    local integer allWood = GetUnitCountDone({wood})\n"
                + "    local integer numWorkers\n" + "".join(x + "\n" for x in self.blocks(ai.harvest, harvest))
                + "endfunction\n\n" + WORKER_ASSIGNMENT)

    def attacking(self) -> str:
        ai = self.ai
        groups = sorted(ai.groups, key=lambda g: g.name)
        number = {g.index: k for k, g in enumerate(groups, 1)}
        waves = len(ai.waves)

        minimum = ["    local integer count", "", "    // Check for attack wave limit", f"    if (attackWave > {waves}) then",
                   "        return false", "    endif", ""]
        group = next((g for g in ai.groups if g.index == ai.minimum_group), None)
        if ai.minimum_group == FIRST_HERO_ONLY or group is None:
            minimum += ["    // First Hero Only", "    if (GetUnitCountDone(hero_id) < 1) then", "        return false",
                        "    endif", ""]
        elif not group.units:
            minimum += [f"    // Attack Group: {group.name}", "    // - No units in this attack group.  Never attack",
                        "    return false"]
        elif all(u.quantity == -1 for u in group.units):
            minimum += [f"    // Attack Group: {group.name}", "    // No specific minimums exist, checking for at least one unit",
                        "    set count = 0"]
            minimum += [f"    set count = count + GetUnitCountDone({self.id(u.id)})" for u in group.units]
            minimum += ["    if (count < 1) then", "        return false", "    endif"]
        else:
            minimum.append(f"    // Attack Group: {group.name}")
            for u in group.units:
                if u.quantity == -1:
                    continue
                lines = [f"set count = GetUnitCountDone( {self.id(u.id)} )", f"if (count < {u.quantity}) then",
                         "    return false", "endif"]
                test = self.test(u.condition_index, u.condition)
                if test is None:
                    minimum += ["    " + x for x in lines]
                else:
                    minimum += [f"    if ({test}) then"] + ["        " + x for x in lines] + ["    endif"]
        if minimum[-1] != "    return false":
            minimum.append("    return true")

        prepare = ["    local integer all", ""]
        for k, g in enumerate(groups, 1):
            if k == 1:
                prepare += [f"    // Attack Group #{k}: {g.name}", f"    if (groupID == {k}) then"]
            else:
                prepare += ["", f"        // Attack Group #{k}: {g.name}", f"    elseif (groupID == {k}) then"]
            for u in g.units:
                uid = self.id(u.id)
                if u.quantity == -1:
                    lines = [f"set all = GetUnitCountDone( {uid} )"]
                    if u.maximum != -1:
                        lines += [f"set all = all - {u.maximum}", "if (all < 0) then", "    set all = 0", "endif"]
                    lines.append(f"call AddAttackUnit( all, all, {uid} )")
                else:
                    lines = [f"call AddAttackUnit( {str(u.quantity) + ',':<4} {str(u.maximum) + ',':<4} {uid} )"]
                test = self.test(u.condition_index, u.condition)
                if test is None:
                    prepare += ["        " + x for x in lines]
                else:
                    prepare += [f"        if ({test}) then"] + ["            " + x for x in lines] + ["        endif"]
        if groups:
            prepare += ["", "    endif"]

        forces = []
        for k, w in enumerate(ai.waves, 1):
            forces += [f"    {'if' if k == 1 else 'elseif'} (attackWave == {k}) then",
                       f"        call PrepareAttackGroup( {number.get(w.group, 0)} )"]
        if ai.waves:
            forces.append("    endif")

        delays = [(0, ai.initial_delay)] + [(k, w.delay) for k, w in enumerate(ai.waves, 1)]
        delays = [(k, d) for k, d in delays if d > 0]
        delay = ["    if (inWave < nextDelay) then", "        return", "    endif", ""]
        for j, (k, d) in enumerate(delays):
            delay += [f"    {'if' if j == 0 else 'elseif'} (inWave == {k}) then", f"        call Sleep( {d} )"]
        if delays:
            delay += ["    endif", ""]
        delay.append("    set nextDelay = inWave + 1")

        update = ["    call AttackWaveDelay( attackWave )", "    set attackWave = attackWave + 1"]
        if ai.repeat_waves:
            update += [f"    if (attackWave > {waves}) then", f"        set attackWave = {waves - ai.repeat_waves + 1}",
                       "        set nextDelay = attackWave + 1", "    endif"]

        def func(comment: str, head: str, lines: list[str]) -> str:
            return _comment(comment) + head + "\n" + "".join(x + "\n" for x in lines) + "endfunction\n\n"

        return (banner("Attacking") + "\n"
                + func("Returns true if the minimum forces for an attack exist",
                       "function HaveMinimumAttackers takes nothing returns boolean", minimum)
                + func("Assigns units to attack based on the given attack group",
                       "function PrepareAttackGroup takes integer groupID returns nothing", prepare)
                + func("Prepares an attack group based on the current attack wave",
                       "function PrepareForces takes nothing returns nothing", forces)
                + func("Sleep delays for each attack wave", "function AttackWaveDelay takes integer inWave returns nothing", delay)
                + func("Advances attack wave counter", "function AttackWaveUpdate takes nothing returns nothing", update)
                + ATTACK_TARGET + self.launch() + self.assignment())

    def launch(self) -> str:
        ai = self.ai
        out = ["    local unit target = null", "    local boolean setAlly = true", "",
               "    // Don't launch any attack while town is threatened", "    if (TownThreatened()) then",
               "        call Sleep( 2 )", "        return", "    endif", ""]
        open_key, depth = None, 1
        for k, p in enumerate(ai.targets, 1):
            ind = "    " * depth
            out.append(f"{ind}// Target Priority #{k}")
            test = self.test(p.condition_index, p.condition)
            key = test
            if open_key is not None and key != open_key:
                out.append("    endif")
                open_key, depth = None, 1
            if test is not None and open_key is None:
                out.append(f"    if ({test}) then")
                open_key, depth = key, 2
            ind = "    " * depth
            out += [ind + line for line in TARGETS[p.target](p)] + [""]
        if open_key is not None:
            out.append("    endif")
        out += ["    // Attack the target and increment attack wave", "    if (target != null) then",
                "        call AttackTarget( target, setAlly )", "        call AttackWaveUpdate(  )", "    else",
                "        // If no target was found, sleep a bit before trying again", "        call Sleep( 20 )", "    endif"]
        return (_comment("Initiates an attack based on target priorities")
                + "function LaunchAttack takes nothing returns nothing\n" + "".join(x + "\n" for x in out)
                + "endfunction\n\n")

    def assignment(self) -> str:
        lines = ["    call StaggerSleep( 0, 2 )", "    if (attackWave == 1) then", "        call AttackWaveDelay( 0 )",
                 "    endif", "    loop", "        loop", "            call UpdateConditions(  )",
                 "            exitwhen (HaveMinimumAttackers() and not CaptainRetreating())", "            call Sleep( 2 )",
                 "        endloop"]
        if self.ai.options & REMOVE_INJURIES:
            lines.append("        call RemoveInjuries(  )")
        lines += ["        call ResetAttackUnits(  )", "        call PrepareForces(  )", "        call LaunchAttack(  )",
                  "    endloop"]
        return (_comment("Determines all attacking assignments") + "function AttackAssignment takes nothing returns nothing\n"
                + "".join(x + "\n" for x in lines) + "endfunction\n\n")

    def main(self) -> str:
        lines = ["    call InitAI(  )"]
        if self.ai.options & SET_PLAYER_NAME:   # the editor does not escape the name (ai_edit refuses quotes)
            lines.append(f'    call SetPlayerName( ai_player, "{self.ai.name}" )')
        lines += ["    call InitOptions(  )", "    call SelectHeroes(  )", "    call CreateCaptains(  )",
                  "    call SetHeroLevels( function ChooseHeroSkill )", "", "    call Sleep( 0.1 )",
                  "    call StartThread( function WorkerAssignment )", "    call StartThread( function AttackAssignment )",
                  "    call PlayGame(  )"]
        return (banner("Main Entry Point") + f"\n{BAR}\nfunction main takes nothing returns nothing\n"
                + "".join(x + "\n" for x in lines) + "endfunction\n\n")


def _target(fetch: str, *extra: str):
    return lambda p: ["if (target == null) then", f"    set target = {fetch}", *extra, "endif"]


TARGETS = {
    0: _target("GetAllianceTarget()", "    if (target != null) then", "        set setAlly = false", "    endif"),
    1: _target("GetExpansionFoe()", "    if (target != null) then", "        set take_exp = false", "    endif"),
    2: _target("GetMegaTarget()"),
    3: _target("GetEnemyExpansion()"),
    4: _target("GetEnemyExpansion()", "    if (target == null) then", "        call StartGetEnemyBase(  )", "        loop",
               "            exitwhen (not WaitGetEnemyBase())", "            call SuicideSleep( 1 )", "        endloop",
               "        set target = GetEnemyBase()", "    endif"),
    5: lambda p: ["if (target == null) then",
                  f"    set target = GetCreepCamp( {p.creep_min}, {p.creep_max}, {'true' if p.flyers else 'false'} )", "endif"],
    6: lambda p: ["if (target == null) then", "    call PurchaseZeppelin(  )", "    return", "endif"],
}

UTILITIES = """
//===========================================================================
function CheckLastCommand takes boolean pop returns integer
    local integer cmd = GetLastCommand()
    if (pop) then
        call PopLastCommand(  )
    endif
    return cmd
endfunction

//===========================================================================
function CheckLastCommandData takes boolean pop returns integer
    local integer data = GetLastData()
    if (pop) then
        call PopLastCommand(  )
    endif
    return data
endfunction

//===========================================================================
function TotalFoodProduced takes nothing returns integer
    return GetPlayerState(ai_player,PLAYER_STATE_RESOURCE_FOOD_CAP)
endfunction

//===========================================================================
function ExpansionNeeded takes nothing returns boolean
    return take_exp
endfunction

//===========================================================================
function BuildExpansion takes integer hallID, integer mineID returns nothing
    if (HallsCompleted(hallID)) then
        call SetBuildExpa( TownCount(hallID) + 1, mineID )
    endif
endfunction

//===========================================================================
function CurrentAttackWave takes nothing returns integer
    return attackWave
endfunction

//===========================================================================
function ResetAttackUnits takes nothing returns nothing
    set awGold = 0
    set awWood = 0
    call InitAssaultGroup(  )
endfunction

//===========================================================================
function AddAttackUnit takes integer minQty, integer maxQty, integer unitID returns nothing
    // Track attacking gold workers
    if (unitID == {gold}) then
        set awGold = awGold + minQty
    endif

    // Track attacking wood workers
    if (unitID == {wood}) then
        set awWood = awWood + minQty
    endif

    call SetAssaultGroup( minQty, maxQty, unitID )
endfunction

"""

CHOOSE_HERO_SKILL = f"""{_comment("Returns the hero skill for the given hero and level")}function ChooseHeroSkill takes nothing returns integer
    local integer curHero = GetHeroId()
    local integer level = GetHeroLevelAI()

    if (level > max_hero_level) then
        set max_hero_level = level
    endif

    if (curHero == hero_id) then
        return skills1[level]
    elseif (curHero == hero_id2) then
        return skills2[level]
    elseif (curHero == hero_id3) then
        return skills3[level]
    endif
    return 0
endfunction

"""

WORKER_ASSIGNMENT = f"""{_comment("Determines all building and harvesting assignments for workers")}function WorkerAssignment takes nothing returns nothing
    loop
        call UpdateConditions(  )

        // Harvesting
        call ClearHarvestAI(  )
        call HarvestPriorities(  )

        // Building
        call InitBuildArray(  )
        call BuildPriorities(  )

        call Sleep( 2 )
    endloop
endfunction

"""

ATTACK_TARGET = f"""{_comment("Basic attack functionality")}function AttackTarget takes unit target, boolean addAlliance returns nothing
    if (target == null) then
        return
    endif
    if (addAlliance) then
        call SetAllianceTarget( target )
    endif
    call FormGroup( 3, true )
    call AttackMoveKillA( target )
    if (not addAlliance) then
        call SetAllianceTarget( null )
    endif
endfunction

"""


def export(ai: wai.AIData, td: TriggerData) -> str:
    """The AI Editor's export of `ai` (CRLF line endings)."""
    g = _Gen(ai, td)
    text = (g.header() + g.globals() + g.utilities() + g.options() + g.conditions() + g.heroes() + g.building()
            + g.attacking() + g.main())
    return text.replace("\n", "\r\n")
