"""Editor-generated script parts from war3map.w3i: the file header, InitUpgrades, InitTechTree, the player setup
functions (InitCustomPlayerSlots, InitCustomTeams, InitAllyPriorities), main and config. Exact on the local JASS
corpus except one credits map whose player sets a race skin without a forced start location."""
import struct
from dataclasses import dataclass
from typing import Callable

from ..formats import w3e, w3i
from ..formats.wts import TriggerStrings

BAR = "//" + "=" * 75
BANNER = "//" + "*" * 75
TITLES = ("Upgrades", "TechTree", "Players", "Main Initialization", "Map Configuration")
MAIN_CALLS = ("InitSounds", "CreateRegions", "CreateCameras", "InitUpgrades", "InitTechTree", "CreateAllDestructables",
              "CreateAllItems", "InitRandomGroups", "CreateAllUnits")
CAMERA_MARGINS = (512, 256, 512, 256)  # left, bottom, right, top: the editor writes bounds minus the game's margins
RACE_PREFERENCE = {1: "RACE_PREF_HUMAN", 2: "RACE_PREF_ORC", 3: "RACE_PREF_UNDEAD", 4: "RACE_PREF_NIGHTELF"}
CONTROLLER = {1: "MAP_CONTROL_USER", 2: "MAP_CONTROL_COMPUTER", 3: "MAP_CONTROL_NEUTRAL", 4: "MAP_CONTROL_RESCUABLE"}
FIXED_START, RACE_SKIN = 0x01, 0x40  # player flags; RACE_SKIN also fixes the start location
FIXED_PLAYER_SETTINGS, CUSTOM_FORCES, TERRAIN_FOG, WATER_TINT = 1 << 5, 1 << 6, 1 << 13, 1 << 16
ALLIED, ALLIED_VICTORY = 1, 2
SHARED = ((1, "Allied", "SetPlayerAllianceStateAllyBJ"), (8, "Shared Vision", "SetPlayerAllianceStateVisionBJ"),
          (16, "Shared Control", "SetPlayerAllianceStateControlBJ"),
          (32, "Shared Advanced Control", "SetPlayerAllianceStateFullControlBJ"))


@dataclass
class MapInfoParts:
    info: w3i.MapInfo
    strings: TriggerStrings
    world_edit: dict  # UI/WorldEditData.txt: section -> key -> value (TerrainLights, UnitLights, Day/NightAmbience)
    terrain: w3e.Terrain | None
    is_ability: Callable[[str], bool]  # tech tree ids that are abilities (not units, items or upgrades)


def _f1(v: float) -> str:
    return f"{v:.1f}"


def _q(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _f32(bits: int) -> float:
    return struct.unpack("<f", struct.pack("<I", bits & 0xFFFFFFFF))[0]


def _banner(title: str) -> str:
    return f"{BANNER}\n//*\n//*  {title}\n//*\n{BANNER}\n\n"


def _function(name: str, lines: list[str]) -> str:
    return f"function {name} takes nothing returns nothing\n" + "".join(x + "\n" for x in lines) + "endfunction\n\n"


def header(p: MapInfoParts) -> str:
    name, author = p.strings.resolve(p.info.name), p.strings.resolve(p.info.author)
    return (f"{BAR}\n// \n// {name}\n// \n//   Warcraft III map script\n//   Generated by the Warcraft III World Editor\n"
            f"//   Map Author: {author}\n// \n{BAR}\n\n")


def _per_player(p: MapInfoParts, entries) -> dict:
    ids = {q.id for q in p.info.players}
    out = {}
    for e in entries:
        for player in sorted(ids):
            if e.players >> player & 1:
                out.setdefault(player, []).append(e)
    return out


def upgrades(p: MapInfoParts) -> str | None:
    per = {}
    for player, entries in _per_player(p, p.info.upgrades).items():
        for u in entries:
            if u.availability in (0, 2):
                levels = per.setdefault(player, {}).setdefault(u.id, {0: [], 2: []})
                levels[u.availability].append(u.level)
    if not per:
        return None
    text = ""
    for player in sorted(per):
        lines = []
        for uid, levels in per[player].items():
            if levels[0]:
                lines.append(f"    call SetPlayerTechMaxAllowed( Player({player}), '{uid.decode('latin-1')}', {min(levels[0])} )")
            if levels[2]:
                lines.append(f"    call SetPlayerTechResearched( Player({player}), '{uid.decode('latin-1')}', "
                             f"{max(levels[2]) + 1} )")
        text += _function(f"InitUpgrades_Player{player}", lines)
    return _banner("Upgrades") + text + _function("InitUpgrades", [f"    call InitUpgrades_Player{x}(  )" for x in sorted(per)])


def techtree(p: MapInfoParts) -> str | None:
    per = _per_player(p, p.info.tech)
    if not per:
        return None
    text = ""
    for player in sorted(per):
        lines = []
        for t in per[player]:
            tid = t.id.decode("latin-1")
            lines.append(f"    call SetPlayerAbilityAvailable( Player({player}), '{tid}', false )" if p.is_ability(tid)
                         else f"    call SetPlayerTechMaxAllowed( Player({player}), '{tid}', 0 )")
        text += _function(f"InitTechTree_Player{player}", lines)
    return _banner("TechTree") + text + _function("InitTechTree", [f"    call InitTechTree_Player{x}(  )" for x in sorted(per)])


def _ally_priorities(p: MapInfoParts) -> list[str]:
    players, lines = p.info.players, []
    for k, player in enumerate(players):
        for low, high, count_fn, prio_fn in ((player.ally_low, player.ally_high, "SetStartLocPrioCount", "SetStartLocPrio"),
                                             (player.enemy_low, player.enemy_high, "SetEnemyStartLocPrioCount",
                                              "SetEnemyStartLocPrio")):
            marked = [(j, q) for j, q in enumerate(players) if (low | high) >> q.id & 1]
            if not marked:
                continue
            lines += ["", f"    call {count_fn}( {k}, {len(marked)} )"]
            others = [(j, q) for j, q in marked if q.id != player.id]
            lines += [f"    call {prio_fn}( {k}, {n}, {j}, {'MAP_LOC_PRIO_LOW' if low >> q.id & 1 else 'MAP_LOC_PRIO_HIGH'} )"
                      for n, (j, q) in enumerate(others)]
    return lines


def players(p: MapInfoParts) -> str:
    mi = p.info
    slots = [""]
    for k, player in enumerate(mi.players):
        pid = f"Player({player.id})"
        slots += [f"    // Player {player.id}", f"    call SetPlayerStartLocation( {pid}, {k} )"]
        if player.flags & (FIXED_START | RACE_SKIN):
            slots.append(f"    call ForcePlayerStartLocation( {pid}, {k} )")
        slots += [f"    call SetPlayerColor( {pid}, ConvertPlayerColor({player.id}) )",
                  f"    call SetPlayerRacePreference( {pid}, {RACE_PREFERENCE.get(player.race, 'RACE_PREF_RANDOM')} )"]
        if player.flags & RACE_SKIN:
            slots.append(f"    call SetPlayerRaceSkin( {pid}, RACE_PREF_USER_SELECTABLE )")
        selectable = not mi.flags & FIXED_PLAYER_SETTINGS or player.race == 0
        slots += [f"    call SetPlayerRaceSelectable( {pid}, {'true' if selectable else 'false'} )",
                  f"    call SetPlayerController( {pid}, {CONTROLLER.get(player.controller, 'MAP_CONTROL_USER')} )"]
        if player.controller == 4:
            slots += [f"    call SetPlayerAlliance( {pid}, Player({q.id}), ALLIANCE_RESCUABLE, true )"
                      for q in mi.players if q.controller == 1]
        slots.append("")
    teams, team = [], -1
    for force in mi.forces:
        members = [q.id for q in mi.players if force.players >> q.id & 1]
        if not members:
            continue
        team += 1
        teams.append(f"    // Force: {force.name}")
        for m in members:
            teams.append(f"    call SetPlayerTeam( Player({m}), {team} )")
            if force.flags & ALLIED_VICTORY:
                teams.append(f"    call SetPlayerState( Player({m}), PLAYER_STATE_ALLIED_VICTORY, 1 )")
        for bit, title, fn in SHARED:
            if force.flags & bit and len(members) > 1:
                teams += ["", f"    //   {title}"]
                teams += [f"    call {fn}( Player({a}), Player({b}), true )" for a in members for b in members if a != b]
        teams.append("")
    priorities = _ally_priorities(p)
    return (_banner("Players") + _function("InitCustomPlayerSlots", slots) + _function("InitCustomTeams", teams)
            + (_function("InitAllyPriorities", priorities) if priorities else ""))


def main(p: MapInfoParts, calls: set[str]) -> str:
    mi, wed = p.info, p.world_edit
    tileset = chr(mi.tileset)
    light = chr(mi.light_environment) if mi.light_environment else tileset
    weather = (mi.v39_after_weather[5].to_bytes(4, "little") if mi.version >= 39 else mi.global_weather)
    lines = ["    local weathereffect we"] if weather != b"\0\0\0\0" else []
    b, (ml, mb, mr, mt) = mi.camera_bounds, CAMERA_MARGINS
    lines.append(
        f"    call SetCameraBounds( {_f1(b[0] - ml)} + GetCameraMargin(CAMERA_MARGIN_LEFT), {_f1(b[1] - mb)} + "
        f"GetCameraMargin(CAMERA_MARGIN_BOTTOM), {_f1(b[2] + mr)} - GetCameraMargin(CAMERA_MARGIN_RIGHT), {_f1(b[3] + mt)} - "
        f"GetCameraMargin(CAMERA_MARGIN_TOP), {_f1(b[4] - ml)} + GetCameraMargin(CAMERA_MARGIN_LEFT), {_f1(b[5] + mt)} - "
        f"GetCameraMargin(CAMERA_MARGIN_TOP), {_f1(b[6] + mr)} - GetCameraMargin(CAMERA_MARGIN_RIGHT), {_f1(b[7] - mb)} + "
        f"GetCameraMargin(CAMERA_MARGIN_BOTTOM) )")
    lights = [wed.get(section, {}).get(light) or wed.get(section, {}).get("L", "") for section in ("TerrainLights", "UnitLights")]
    lines.append(f"    call SetDayNightModels( {_q(lights[0])}, {_q(lights[1])} )")
    if mi.flags & TERRAIN_FOG:
        c = mi.fog_color
        fog = f"{mi.fog_style}, {_f1(mi.fog_start_z)}, {_f1(mi.fog_end_z)}, {mi.fog_density:.3f}"
        rgb = f"{c[2] / 255:.3f}, {c[1] / 255:.3f}, {c[0] / 255:.3f}"
        if mi.version >= 39:
            # ponytail: the four extra fog values and the draw-over-sky flag are read from the v39 bytes in the order
            # that reproduces every local map; their editor fields are not identified yet
            extra = mi.v39_after_weather
            lines += [f"    call SetTerrainFogExV( {fog}, {_f1(_f32(int.from_bytes(mi.global_weather, 'little')))}, "
                      f"{_f1(_f32(extra[0]))}, {_f1(_f32(extra[1]))}, {_f1(_f32(extra[2]))}, {rgb} )",
                      f"    call BlzSetTerrainFogMaxLinearDensity( {_f1(_f32(extra[3]))} )",
                      f"    call BlzSetTerrainFogDrawOverSky( {'true' if extra[4] else 'false'} )"]
        else:
            lines.append(f"    call SetTerrainFogEx( {fog}, {rgb} )")
    if mi.flags & WATER_TINT:
        t = mi.water_tint
        lines.append(f"    call SetWaterBaseColor( {t[2]}, {t[1]}, {t[0]}, {t[3]} )")
    if mi.version >= 39:
        # ponytail: only one of these HD water values varies in the local maps (10 or 50); the rest are constants
        lines.append(f"    call SetHDWaterParamsEx( 0, 0, 0, false, 20, 0, 100, 10, 0, {mi.v39_after_zoom[4]}, 100, 100 )")
    if weather != b"\0\0\0\0":
        t = p.terrain
        area = (t.offset_x, t.offset_y, t.offset_x + (t.width - 1) * 128, t.offset_y + (t.height - 1) * 128) if t else (0, 0, 0, 0)
        lines += [f"    set we = AddWeatherEffect( Rect({','.join(_f1(v) for v in area)}), '{weather.decode('latin-1')}' )",
                  "    call EnableWeatherEffect( we, true )"]
    lines += [f"    call NewSoundEnvironment( {_q(mi.sound_environment or 'Default')} )",
              f"    call SetAmbientDaySound( {_q(wed.get('DayAmbience', {}).get(tileset, ''))} )",
              f"    call SetAmbientNightSound( {_q(wed.get('NightAmbience', {}).get(tileset, ''))} )",
              '    call SetMapMusic( "Music", true, 0 )']
    lines += [f"    call {fn}(  )" for fn in MAIN_CALLS if fn in calls]
    lines += ["    call InitBlizzard(  )", "    call InitGlobals(  )", "    call InitCustomTriggers(  )",
              "    call RunInitializationTriggers(  )", ""]
    return _banner("Main Initialization") + BAR + "\n" + _function("main", lines)


def config(p: MapInfoParts, ally_priorities: bool) -> str:
    mi = p.info
    users = sum(q.controller == 1 for q in mi.players)
    lines = [f"    call SetMapName( {_q(mi.name)} )", f"    call SetMapDescription( {_q(mi.description)} )",
             f"    call SetPlayers( {len(mi.players)} )", f"    call SetTeams( {len(mi.players)} )",
             f"    call SetGamePlacement( {'MAP_PLACEMENT_USE_MAP_SETTINGS' if users == 1 else 'MAP_PLACEMENT_TEAMS_TOGETHER'} )",
             ""]
    lines += [f"    call DefineStartLocation( {k}, {_f1(q.start_x)}, {_f1(q.start_y)} )" for k, q in enumerate(mi.players)]
    lines += ["", "    // Player setup", "    call InitCustomPlayerSlots(  )"]
    if mi.flags & CUSTOM_FORCES:
        lines.append("    call InitCustomTeams(  )")
    else:
        lines += [f"    call SetPlayerSlotAvailable( Player({q.id}), MAP_CONTROL_USER )" for q in mi.players]
        lines.append("    call InitGenericPlayerSlots(  )")
    if ally_priorities:
        lines.append("    call InitAllyPriorities(  )")
    return _banner("Map Configuration") + _function("config", lines)


def tail(p: MapInfoParts, calls: set[str]) -> dict:
    """Section texts by title (Upgrades and TechTree None when absent) and `calls`, the managed main calls."""
    out = {"Upgrades": upgrades(p), "TechTree": techtree(p)}
    calls = set(calls) - {"InitUpgrades", "InitTechTree"}
    calls |= {fn for fn, title in (("InitUpgrades", "Upgrades"), ("InitTechTree", "TechTree")) if out[title]}
    out["Players"] = players(p)
    out["Main Initialization"] = main(p, calls)
    out["Map Configuration"] = config(p, "function InitAllyPriorities" in out["Players"])
    return out
